# Generated by Django 4.2.5 on 2023-09-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='story',
            field=models.TextField(max_length=5000),
        ),
    ]
