# Generated by Django 4.2.5 on 2023-09-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_problems_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='story',
            field=models.TextField(max_length=50000),
        ),
    ]
