# Generated by Django 4.2.5 on 2023-10-04 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0006_alter_problems_resolved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='resolved_user',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
